import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        surface: "#fbf9f6",
        "surface-dim": "#dbdad7",
        "surface-bright": "#fbf9f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f0",
        "surface-container": "#efeeeb",
        "surface-container-high": "#eae8e5",
        "surface-container-highest": "#e4e2df",
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#444748",
        "inverse-surface": "#30312f",
        "inverse-on-surface": "#f2f0ed",
        outline: "#747878",
        "outline-variant": "#c4c7c7",
        primary: "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1c1b1b",
        "on-primary-container": "#858383",
        secondary: "#735c00",
        "on-secondary": "#ffffff",
        "secondary-container": "#fed65b",
        "secondary-fixed": "#ffe088",
        "on-secondary-container": "#745c00",
        tertiary: "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1d1b1a",
        gold: "#d4af37",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#fbf9f6",
        "on-background": "#1b1c1a",
        "surface-variant": "#e4e2df",
        "surface-subtle": "#e8e4de",
        "pure-white": "#ffffff",
        "text-main": "#1a1a1a",
      },
      fontFamily: {
        display: ["Montserrat", "sans-serif"],
        body: ["Inter", "sans-serif"],
        "display-xl": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["80px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "1", letterSpacing: "0.15em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "400" }],
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "section-gap": "120px",
        "gutter-grid": "2px",
      },
      letterSpacing: {
        tightest: "-0.04em",
      },
    },
  },
  plugins: [],
};

export default config;